// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRlQ4v2QZll-GGDKv3i5GX23V6wEQSWko',
    appId: '1:205131740686:web:8762ee02f3b67f6d676e5f',
    messagingSenderId: '205131740686',
    projectId: 'cleanslate-57c70',
    authDomain: 'cleanslate-57c70.firebaseapp.com',
    storageBucket: 'cleanslate-57c70.appspot.com',
    measurementId: 'G-GGPCW454ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZ9W0tjls3lCliftJPHlozhWhJ8gxGao',
    appId: '1:205131740686:android:d91956040943335d676e5f',
    messagingSenderId: '205131740686',
    projectId: 'cleanslate-57c70',
    storageBucket: 'cleanslate-57c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6tTKBrY-986HH3SNZjW9afa_l1WksWbs',
    appId: '1:205131740686:ios:26cd447c83bb80ac676e5f',
    messagingSenderId: '205131740686',
    projectId: 'cleanslate-57c70',
    storageBucket: 'cleanslate-57c70.appspot.com',
    iosClientId: '205131740686-b6gbamcqq3b3nj0c2h23iamlt5tplt03.apps.googleusercontent.com',
    iosBundleId: 'com.example.hms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6tTKBrY-986HH3SNZjW9afa_l1WksWbs',
    appId: '1:205131740686:ios:26cd447c83bb80ac676e5f',
    messagingSenderId: '205131740686',
    projectId: 'cleanslate-57c70',
    storageBucket: 'cleanslate-57c70.appspot.com',
    iosClientId: '205131740686-b6gbamcqq3b3nj0c2h23iamlt5tplt03.apps.googleusercontent.com',
    iosBundleId: 'com.example.hms',
  );
}
